---
- name: Ansible service module example
# Defining the remote server where the package will be deployed 
  hosts: localhost
  remote_user: ubuntu   # Using Remote user as ubuntu
  become: true
  tasks:  

# Starting the apache web server on a remote node ( TASK-1) 
    - name: Start service apache, if not started
      ansible.builtin.service:
        name: apache2
        state: started

# Enabling the apache web server on the remote node ( TASK-2) 
    - name: Enabling the apache service and not touching the state
       ansible.builtin.service:
         name: apache2
         enabled: yes

# Stoping the Splunk service on the remote node ( TASK-3) 
    - name: Stoping the Splunk service, if started
      ansible.builtin.service:
        name: splunkd
        state: stopped

# Restarting the Splunk service on the remote node ( TASK-4) 

    - name: Restart service Apache2, in all cases
      ansible.builtin.service:
        name: apache2
        state: restarted

# Reloading the Splunk service on the remote node ( TASK-5) 

    - name: Reload service docker, in all cases
      ansible.builtin.service:
        name: docker
        state: reloaded

# Restarting the Tomcat service on the remote node ( TASK-6) 

    - name: Restart tomcat service
      ansible.builtin.service:
       name: tomcat
       state: restarted

