---
- hosts: all
  name: restart sshd
  remote_user: ubuntu
  become: true
  become_method: sudo
  tasks:
    - name: Start service ssh, if not started
      ansible.builtin.systemd:
        name: sshd
        state: restarted
